export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import MainLayout from "@/component/Layout/Layouts"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
